### ISSUE TITLE
failed to switch on Actor 'NoneType' object has no attribute 

### ISSUE THREAD

**Issue by Misterobots** [hurra/cbpi4-http-actor#2]
Hello! I keep receiving this error when attempting to activate the http-actor. "failed to switch on Actor 'NoneType' object has no attribute" . I'm not sure if you have any insight on this error, but I cannot seem to be able to figure it out.  Thank you!

**Comment by hurra** [comment]
Are there any more error messages? The error message is quite generic.
Maybe you can upload a screenshot?

**Comment by Misterobots** [comment]
I apologize, "failed to switch on Actor 'NoneType' object has no attribute 'replace'  "

First error when turning actor 'on' : 
2021-12-04:16:43:34,919 ERROR    [actor_controller.py:22] Failed to switch on Actor DNq3KWRNowgxeCodkDWxBr 'NoneType' object has no attribute 'replace'
2021-12-04:16:43:34,924 INFO     [web_log.py:206] 192.168.1.190 [04/Dec/2021:21:43:34 +0000] "POST /actor/DNq3KWRNowgxeCodkDWxBr/on HTTP/1.1" 204 138 "http://192.168.1.190:8000/cbpi_ui/static/index.html"




Error when switching actor 'off' : 
--- Logging error ---
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/cbpi/controller/actor_controller.py", line 28, in off
    await item.instance.off()
  File "/usr/local/lib/python3.9/dist-packages/cbpi4-http-actor/__init__.py", line 115, in off
    await self.start_request(False)
  File "/usr/local/lib/python3.9/dist-packages/cbpi4-http-actor/__init__.py", line 98, in start_request
    logger.info("HTTPActor type=request_start onoff=%s url=\"%s\" payload=\"%s\" method_getpost=%s" % (onoff, url, payload.replace('"', '\\"'), self.httpmethod_get))
AttributeError: 'NoneType' object has no attribute 'replace'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/logging/__init__.py", line 1079, in emit
    msg = self.format(record)
  File "/usr/lib/python3.9/logging/__init__.py", line 923, in format
    return fmt.format(record)
  File "/usr/lib/python3.9/logging/__init__.py", line 659, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.9/logging/__init__.py", line 363, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/local/bin/cbpi", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/cbpi/cli.py", line 352, in start
    cbpi.start()
  File "/usr/local/lib/python3.9/dist-packages/cbpi/craftbeerpi.py", line 289, in start
    web.run_app(self.init_serivces(), port=self.static_config.get("port", 2202))
  File "/usr/local/lib/python3.9/dist-packages/aiohttp/web.py", line 508, in run_app
    loop.run_until_complete(main_task)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 629, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.9/asyncio/base_events.py", line 596, in run_forever
    self._run_once()
  File "/usr/lib/python3.9/asyncio/base_events.py", line 1890, in _run_once
    handle._run()
  File "/usr/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.9/dist-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.9/dist-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/dist-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/local/lib/python3.9/dist-packages/aiohttp/web_middlewares.py", line 110, in impl
    return await handler(request)
  File "/usr/local/lib/python3.9/dist-packages/aiohttp_session/__init__.py", line 154, in factory
    response = await handler(request)
  File "/usr/local/lib/python3.9/dist-packages/aiohttp_auth/auth/auth.py", line 27, in _middleware_handler
    response = await handler(request)
  File "/usr/local/lib/python3.9/dist-packages/cbpi/craftbeerpi.py", line 60, in error_middleware
    response = await handler(request)
  File "/usr/local/lib/python3.9/dist-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/local/lib/python3.9/dist-packages/cbpi/api/decorator.py", line 39, in wrapper
    return await func(*args)
  File "/usr/local/lib/python3.9/dist-packages/cbpi/http_endpoints/http_actor.py", line 173, in http_off
    await self.controller.off(id)
  File "/usr/local/lib/python3.9/dist-packages/cbpi/controller/actor_controller.py", line 32, in off
    logging.error("Failed to switch on Actor {} {}".format(id, e), True)
Message: "Failed to switch on Actor DNq3KWRNowgxeCodkDWxBr 'NoneType' object has no attribute 'replace'"
Arguments: (True,)
2021-12-04:16:47:56,773 INFO     [web_log.py:206] 192.168.1.190 [04/Dec/2021:21:47:56 +0000] "POST /actor/DNq3KWRNowgxeCodkDWxBr/off HTTP/1.1" 204 138 "http://192.168.1.190:8000/cbpi_ui/static/index.html"


thank you!

**Comment by hurra** [comment]
Did you specify a `Request Body On` or `Request Body Off`?

**Comment by Misterobots** [comment]
> Did you specify a `Request Body On` or `Request Body Off`?

I did not. Is this a requirement? I have it just sending a the get request in the url.

**Comment by Misterobots** [comment]
With the http-actor in cbpi3, I could send a direct url to the esp8266 such as. http://192.168.1.162/control?cmd=GPIO,14,0 , I understand this plugin is not that. Just would like to understand what I need to change. Thank you!

**Comment by hurra** [comment]
HI,

i think this plugin is the one for you! :)
Right now it seems that you need to specify a `Request Body On` and `Request Body Off`.

I will release a new version today, which makte those two options optional.

- hurra

**Comment by hurra** [comment]
I released 0.0.3 with a fix: 
* https://github.com/hurra/cbpi4-http-actor/releases/tag/0.0.3
* https://pypi.org/project/cbpi4-http-actor/0.0.3/

Can you confirm that it is working now?

**Comment by Misterobots** [comment]
Yes! It working exactly as expected! Thank you so much for the update!
